config/webpackDevServer.config.js, public/inputServiceWorker.js, src/Backend.ts, src/Constants.ts, src/Papyros.ts, src/index.ts, src/util/Logging.ts, src/workers/javascript/index.ts, src/workers/python/index.ts, src/workers/python/init.py.ts
Contains fixes for the following features:
Where possible, console.log and similar calls have been replaced by calls to papyrosLog, to reduce the amount of logs in production that might be useful in development.
The inputServiceWorker now adds extra headers to responses from requests for urls within our domain, allowing the use of SharedArrayBuffers even in GitHub pages. Locally this worked thanks to the webpack-devServer, but these headers are not added by GitHub. Now the more efficient input calls should work in supporting browsers. This logic has also been moved to index.ts, as it relies on a reload of the page. After starting the service worker, we need a reload to ensure that our page is fetched with the correct headers. A key in localStorage tells the app whether it can proceed or …
=> Fix a lot of things

src/workers/python/PythonWorker.worker.ts, src/workers/python/init.py.ts
Closes #16
This PR allows doctests to work by doing the following:\
setting the module name to __main__ instead of builtins\
Changing the way the scoping works to allow doctest to find the relevant docstrings. This requires running the code in the global scope, and then resetting the scope to undo changes (preventing declared variables from being found later, as well as undoing overrides of builtins)\
Better conversion of PyProxy objects to actual JS objects to prevent type errors.
=> Fix running code containing Python doctests

.eslintrc, build/index.html, package.json, src/BackendManager.ts, src/CodeEditor.ts, src/Constants.ts, src/Papyros.ts, src/ProgrammingLanguage.ts, yarn.lock
This pull request replaces the text area to enter code with an instance of [CodeMirror 6](https://codemirror.net/6/).
CM6 was chosen over alternatives such as Ace and Monaco because of its better documentation and extensibility.
For now, only basic features such as line numbers, auto-closing brackets and syntax highlighting are supported. It is possible to enable more advanced language features such as auto-complete and highlighting incorrect syntax, but they will be added in a later update as part of #46.
Closes #2 
Closes #34
=> Add CodeMirror 6 editor

package.json, src/CodeEditor.ts, src/Papyros.ts, yarn.lock
Depends on #43 
Closes #37 
By using a Compartment, changes to extensions in the CodeEditor can be done without recreating the entire editor. 
I used this approach for both the LanguageSupport and the indentUnit facets, allowing both to be updated more easily. This would allow us to let the user choose the amount of used spaces (with the default being 4).
=> Allow configuring indent size

build/index.html, src/Constants.ts, src/Papyros.ts, src/index.ts
This PR adds a config object to Papyros, with a new addition called standAlone. This boolean option tells Papyros to work in stand-alone mode, meaning it is its own application and not part of something bigger (such as Dodona).  This allows for conditional styling and rendering, as not every feature is relevant when not in stand-alone mode (such as a selector for the programming language, as this is most likely fixed and provided by the caller). The bar above the editor would then look like this:
The current usage is disabling/enabling the header (containing the title and the language select) and the programming language select.
The stand-alone mode can thus now dynamically be translated by using urlParams, as follows.
This option could be used la
ter on to disable/enable other features …
=> Add stand alone mode

src/Papyros.ts
This PR adds finer control over when the terminate button is visible. The original code only compared to Ready, whereas Loading is also a state that should be preserved.
As a bonus, I added logs and  early returns when runCode/terminate are called from states when they shouldn't be callable. This should only occur when a user tampers with the DOM, but might also protect against coding errors.
Closes #61
=> Show terminate button only when appropriate

src/Backend.ts, src/Papyros.ts, src/workers/python/PythonWorker.worker.ts
This PR restores the functionality of input() in Python. The callback returned void, causing input to never receive a value and thus printing None. This is tied to the fact that I always print the value that the user gave. In a terminal, after calling input, the user is expected to type something and hit enter. This behaviour is emulated in the output window, by printing the prompt and then the obtained value. I noticed this causes some confusion, so this might only be desirable in an explicit REPL environment. The question is thus whether this extra print should also be removed as part of this PR.
Closes #56 
Can close #27  @pdawyndt ?
=> Fix callback return value

.github/workflows/deploy-pages.yaml, .github/workflows/validate-translations.yaml, .gitignore, ValidateTranslations.js, package.json, scripts/ValidateTranslations.js, src/Papyros.ts, src/Translations.js, yarn.lock
This PR adds a JS script called ValidateTranslations that checks whether the provided translations are valid. A GitHub action is also defined to call this script on pushes to any branch.
The script is written in JavaScript as running it as a stand-alone TS file never fully worked. On the one hand, i18n-extract does not provide proper typing, requiring some hacks to get it into TypeScript (e.g. including the source code directly as it required some manual editing to even run). On the other hand, importing other modules did not work out of the box.
The JavaScript file can easily be run through Node, but the Translations.ts file had to be converted to JS for it to be imported. This isn't an impactful change, as they are simple objects where typing is quite irrelevant.
The current checks are: …
=> Validate translations

src/OutputManager.ts, src/Papyros.css
Examples:
As you can see this is especially important for indicating the location of syntax errors.
Related:
- #39
- #58
=> Preserve whitespace in output area

src/Papyros.css, src/Papyros.ts, src/examples/PythonExamples.ts, src/workers/python/PythonWorker.worker.ts, src/workers/python/init.py
Part 1 of #63. Uses https://github.com/alexmojaki/python_runner which takes care of things like input and output and is used by futurecoder.
`python_runner` buffers output internally which helps a lot with #17.
Also in this PR:
- Replace `\\n` (introduced in my previous PR #92) with `\n`
- Only install `matplotlib` when it's imported by the user's code, greatly speeding up startup.
=> Use python_runner

.github/workflows/deploy-pages.yaml
This PR provides support for deploying two versions of Papyros: the main branch that aligns with the current release, and a dev version to try things out in the browser.
Two URLs are now supported:
main version on https://papyros.dodona.be
dev version (current branch): https://papyros.dodona.be/dev/  (the trailing slash is imported to be routed to index.html, unclear why no automatic redirect is done)
Finishes a task of #133
=> Main and dev GitHub-pages

package.json, src/BackendManager.ts
Halting event publishing should make messages come through more reliabily. It still sometimes takes a while for the interrupt to get through, but I'm not sure what causes that. 
Closes #158
=> Halt event publishing after interrupt/end

src/CodeEditor.ts, src/CodeRunner.ts, test/__tests__/CodeEditor.test.ts
This PR changes some keybinds.
Ctrl-Enter can now be used to run the code without needing to click the button
The original keybinding (insertBlankLine) is now assigned to Shift-Enter, similar to how other editors handle this (like the GitHub comment window here)
Closes #36
=> feat: Add keybind to run code

src/workers/javascript/JavaScriptWorker.worker.ts, src/workers/python/PythonWorker.worker.ts
A small oversight caused JavaScript events to not be flushed and thus not be visible for the user.
Closes #235
=> Properly handle JavaScript events

src/CodeRunner.ts, src/editor/BatchInputEditor.ts
By simplifying the code that handles the supplied lines in batch mode, empty lines should not be misinterpreted. Issue was caused by older code that was written when lines were handled as DOM elements instead.
Closes #254
=> Correct batch input handling

package.json, src/workers/python/PythonWorker.worker.ts, yarn.lock
Update to version `1.3.1` instead of `1.3.3` as `1.3.3` no longer provides types and compiles to umd.
This caused a lot of complications that weren't easy to fix. I chose `1.3.1` as I already had that version working in https://github.com/dodona-edu/pyodide-trace-library
I made an issue in https://github.com/alexmojaki/pyodide-worker-runner/issues/32 to fix this so hopefully we can still easily update to future versions
=> Update pyodide worker runner

package.json, scripts/ValidateTranslations.js, src/CodeRunner.ts, src/Debugger.ts, src/OutputManager.ts, src/Papyros.css, src/Papyros.ts, src/Translations.js, src/editor/CodeEditor.ts, src/editor/DebugExtension.ts, src/editor/Gutters.ts, src/editor/LineEffectExtension.ts, src/editor/TestCodeExtension.ts, src/input/BatchInputHandler.ts, src/input/InteractiveInputHandler.ts, src/input/UserInputHandler.ts, src/util/Rendering.ts
This pr improves the debug state of the editor.
When a debug run is started, the editor becomes readonly.
All visualization of generated output, input used and active line is now based on the shown frame instead of the current phase of execution.
While the debug mode is active, the buttons to start a new execution are replaced by an end debug mode button.
closes #628 #623 #611
=> Add clearer debug state for editor

scripts/ValidateTranslations.js
This improves handling of `if __name__="__main__"`. which will now be treated the same as in the dodona judge.
It is still posible to get similar behaviour with `if __name__="sandbox"`
=> Use custom module name

src/CodeRunner.ts
This pr separates the delay for rendering code buttons and user buttons.
The original implementation caused a bug. As both used the same delay function, calling rerender on the code buttons could cancel the rendering of the user buttons.
related to https://github.com/dodona-edu/dodona/issues/5807
=> Separate delay of code buttons and user buttons

src/workers/python/papyros/papyros.py
The doctest parsers sometimes fails to parse the file.
Eg if you put `>>>print(repr(boom))` either in the code or in a doctests, this will crash the parser.
I have chosen to simply return `false` on `has_doctests` in this case.
We might want to show a proper error message to the user in the future.
closes [#870](https://github.com/dodona-edu/papyros/issues/870)
=> Ignore doctest parsing failures
